name: Fourth Action
on:
  push:
    branches:
      - main
env:
  REACT_HEADING: My App
  REACT_TEST_2: ${{secrets.REACT_TEST}}
jobs:
  test:
    env:
      REACT_SUBHEADING: Subheading
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v6
      - name: cache dep
        id: cache
        uses: actions/cache@v5.0.5
        with:
          path: node_modules
          key: deps-node-modules-{{ hashFiles('**/package-lock.json') }} #retriev cache in future
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Test code
        continue-on-error: true
        run: npm run test
        id: run-tests
      - name: Upload artifact
        # if: failure() &&  steps.run-tests.outcome == 'failure' 
        uses: actions/upload-artifact@v7.0.1
        with:
          name: test-report
          path: test.json
  build:
    runs-on: ubuntu-latest
    needs: test
    outputs:
      script-file: ${{ steps.publish.outputs.script-file }}
    steps:
      - name: Get Code
        uses: actions/checkout@v6
      - name: cache dep
        id: cache
        uses: actions/cache@v5.0.5
        with:
          path: node_modules
          key: deps-node-modules-{{ hashFiles('**/package-lock.json') }} #retriev cache in future
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build app
        run: npm run build
      - name: Publish js filename
        id: publish
        run: find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
      - name: Upload artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: dist-files
          # path: |
          #   dist
          #   package.json
          path: dist
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v8.0.1
        with:
          name: dist-files
      - name: Output Content
        run: ls
      - name: Output filename
        run: echo "${{ needs.build.outputs.script-file }}"
      - name: Deploy
        run: |
          echo "Deploying... $REACT_HEADING ${{ env.REACT_HEADING}}"
          echo "Env from Github Secret $REACT_TEST " #this will not work
          echo "Env from Github Secret $REACT_TEST_2 "
  deploy2:
    needs: build
    uses: ./.github/workflows/reusable-sixth.yml
    with:
      artifact-name: dist-files
    secrets:
      some-secrets: ${{secrets.REACT_TEST}}
  report:
    needs: test
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Ouput Info
        run: |
          echo "Something went worng"
          echo "${{github}}"
