name: Third Action
on:
  pull_request:
    types: 
      - opened
    branches:
      - main
      - 'dev-*' # any charachter other than slashes Ex: dev-my-feature
      - 'feat/**' # any character with slashes Ex: feat/hobby/kitchen
  workflow_dispatch:    
  push:
    branches:
      - main
      - 'dev-*' # any charachter other than slashes Ex: dev-my-feature
      - 'feat/**' # any character with slashes Ex: feat/hobby/kitchen
    paths-ignore: #
      - '.github/workflows/*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v6
      - name: Install dependencies
        run: npm ci
      - name: Test app
        run: npm run test
      - name: Build app
        run: npm run build
      - name: Deploy
        run: echo "Deploying..."
